[package]
name = "bellperson-emulated"
version = "0.1.0"
edition = "2021"

[dependencies]
bellperson = "0.24.1"
ff = { version = "0.12.0", features = ["derive"] }
num-bigint = { version = "0.4.3", features = ["rand"] }
num-traits = "0.2.15"

[dev-dependencies]
pasta_curves = { version = "0.5.2", package = "fil_pasta_curves" }
rand = "0.8.5"
